/**
 * Created by Jayakumar Mogenahall on 07/02/2023.
 */
@IsTest
public with sharing class MaterialProcessTest {

//    @IsTest
//    static void Test1(){
//        Test.setMock(HttpCalloutMock.class, new CustomerProcessTest() );
//        String json = '{"materialDescription" : "Hello World","dimensions":{"dimType":"testDimType"},"codes":{"eanCode":"Ab23"},"region":{"countryCode":"Gb"},"additionalInfo":{"info1":"tstInfo1"},"origin":{"originApplication":"OrignApp"}}';
//        MaterialRequestWrapper process = MaterialRequestWrapper.parse(json);
//        System.debug('#process:'+process);
//    }
//
//    public HttpResponse respond(HttpRequest request) {
//        HttpResponse response = new HttpResponse();
//        response.setHeader('Content-Type','x-www-form-urlencoded');
//        response.setBody('{"result":"OK"}');
//        response.setStatusCode(200);
//        return response;
//    }
}