/**
 * Created by Jayakumar Mogenahall on 15/03/2023.
 */

public with sharing class OrderLineModel {

        public Integer deliveryLine;
        public Integer quantity;
        public Double unitPrice;
        public String orderUom;
        public String productName;
        public String productCode;
        public Double unitTax;
        public Double taxRate;
        public String materialCode;
        public String materialNumber;

}